### ISSUE TITLE
Det sørsamiske ordet bïjre blir merket som feilstaving

### ISSUE THREAD

**Issue by albbas** [divvun/divvunspell-swift#3]
Dette skjer i Pages og TextEdit, ikke i SubEthaEdit.

Eksempeltekst: `bïjre bïjre. aalkoe aalkoe. bïjre bïjre. aalkoe aalkoe.`

**Comment by bbqsrc** [comment]
Cannot reproduce. 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/279099/207044487-ba4e20ef-244e-4a5e-9976-d3c658a41400.png">

**Comment by bbqsrc** [comment]
If you can reproduce after updating the relevant spellers etc, open a new issue.
